### ISSUE TITLE
unknown encoding name - bom|utf-8 

### ISSUE THREAD

**Issue by jcoyne** [alphabetum/iso-639#12]
When upgrading to iso-639 0.3.1 (from 0.2.8) I get this error:   

```
  Gem Load Error is: unknown encoding name - bom|utf-8
  Backtrace for gem load error is:
  /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/csv.rb:1532:in `find'
  /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/csv.rb:1532:in `initialize'
  /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/csv.rb:1280:in `new'
  /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/csv.rb:1280:in `open'
  /home/travis/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/csv.rb:1141:in `foreach'
  /home/travis/build/sul-dlss/gis-robot-suite/vendor/bundle/ruby/2.5.0/gems/iso-639-0.3.1/lib/iso-639.rb:24:in `each'
  /home/travis/build/sul-dlss/gis-robot-suite/vendor/bundle/ruby/2.5.0/gems/iso-639-0.3.1/lib/iso-639.rb:24:in `block in <class:ISO_639>'
```

**Comment by jcoyne** [comment]
It looks like this was introduced in 
https://github.com/alphabetum/iso-639/commit/d8d5c8e1a0a87b7932f086bab4555a10ee1ca58b#diff-3a59e89f3aced10aa5fde1f4d55cf25bR23

**Comment by jcoyne** [comment]
It doesn't look like this is a valid encoding in ruby since at least 2.4.3:

```
$ irb
irb(main):001:0> Encoding.find("bom|utf-8")
Traceback (most recent call last):
        5: from /Users/jcoyne85/.rbenv/versions/2.6.5/bin/irb:23:in `<main>'
        4: from /Users/jcoyne85/.rbenv/versions/2.6.5/bin/irb:23:in `load'
        3: from /Users/jcoyne85/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):1
        1: from (irb):1:in `find'
ArgumentError (unknown encoding name - bom|utf-8)
```

**Comment by alphabetum** [comment]
Thanks for the heads up! This was a weird one. `CSV.foreach` has different implementations and behaviors  in different Ruby versions. 'bom|utf-8' is apparently broken in `CSV.foreach` only in Ruby 2.5 (it works in earlier and later versions), but works with `File.open` in Ruby 2.5 and all other tested Ruby versions. Additionally, CSV converters seem to not work properly only in Ruby 2.4, but it's not clear why. I was able to circumvent these issues by doing everything more manually, using `File.open`, `CSV.new`, and `#map` instead of a converter.

As of iso-639 version 0.3.3, tests pass for me in Ruby 2.4 through 2.7. Let me know if you run into additional issues related to this.

**Comment by jcoyne** [comment]
Thank you.
