### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by avit** [alphabetum/iso-639#5]
There are a lot of duplicate string objects (especially empty strings) being allocated.

These are really meant to be read-only lookup tables, so freezing makes sense in that regard.

I have the following monkey-patch, I wonder if this would be worthwhile to freeze everything for optimization:

```
require 'iso-639'

ISO_639::ISO_639_2.each do |entry|
  entry.each do |str|
    str.freeze
  end
  entry.freeze
end
ISO_639::ISO_639_2.freeze
```

**Comment by avit** [comment]
Thanks for releasing the recent update. 

Please let me know your thoughts on this proposal, I would be happy to prepare a pull request if you think it could be merged.

**Comment by alphabetum** [comment]
All values assigned to constants are now frozen in version 0.2.7.

Although a large number of objects are created, as far as I know (please correct me if I'm wrong) they are only initialized once when the constants are assigned, which occurs when the file is loaded with `require`.

In order to get some insight into the object allocation stats, there is a new script that prints how many objects are allocated of each type:

https://github.com/alphabetum/iso-639/blob/aa48c4f/test/allocation_stats

The approach to `freeze` that I just added ends up creating an additional 970 `Array` objects in Ruby 2.3.1p112, but it also appears to eliminate a few thousand `String` objects in Ruby 2.3+.

Regardless of the object allocation issue, these needed to be frozen anyway since they are intended to be immutable constants.

Let me know if you have any feedback.

**Comment by avit** [comment]
Yeah, that works too. I think this is mostly a micro-optimization: it's mostly the strings that get reused downstream and not the arrays so I wouldn't worry about it. I'm not sure where the extra arrays are coming from. Maybe GC would clean them up after the declarations & freezing is done?

Let's close this, we're done here! :smile:
